# Generated by Django 5.1.2 on 2024-11-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_developer_business_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='business_registration_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='organization_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='organization_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='woreda',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
