# Generated by Django 5.1.2 on 2024-11-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_developer_business_registration_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
