# Generated by Django 5.1.2 on 2024-11-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_developer_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='developer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
