# Generated by Django 5.1.2 on 2024-12-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_developer_is_approved_developer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
