# Generated by Django 5.1.2 on 2024-10-21 12:00

import apps.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('app_version', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Finance', 'Finance')], max_length=50)),
                ('supported_platforms', models.CharField(choices=[('Android', 'Android')], max_length=50)),
                ('apk_file', models.FileField(upload_to='apk_files/', validators=[apps.validators.validate_apk])),
                ('app_icon', models.ImageField(upload_to='icons/', validators=[apps.validators.validate_icon])),
                ('cover_graphics', models.ImageField(upload_to='covers/', validators=[apps.validators.validate_cover_graphics])),
                ('screenshots', models.ImageField(upload_to='screenshots/', validators=[apps.validators.validate_screenshot])),
                ('promotional_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('description', models.TextField(max_length=1000)),
                ('tags', models.CharField(max_length=255)),
                ('privacy_policy_url', models.URLField()),
                ('release_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
