# Generated by Django 5.1.2 on 2024-11-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apk_file',
            field=models.FileField(upload_to='apk_files/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_icon',
            field=models.ImageField(upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='cover_graphics',
            field=models.ImageField(upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='screenshots',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
