# Generated by Django 5.1.2 on 2024-12-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_app_apk_file_alter_app_app_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='screenshots',
        ),
    ]
