# Generated by Django 5.1.2 on 2024-12-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_app_screenshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='supported_platforms',
            field=models.CharField(choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=50),
        ),
    ]
