# Generated by Django 5.1.2 on 2024-12-12 06:38

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='ios_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='supported_platforms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=11),
        ),
    ]
