# Generated by Django 5.1.2 on 2024-12-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_app_ios_url_alter_app_supported_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='web_portal',
            field=models.URLField(blank=True, null=True),
        ),
    ]
