# Generated by Django 5.1.2 on 2024-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_app_web_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(max_length=100000),
        ),
    ]
