# Generated by Django 5.1.2 on 2024-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_app_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_version',
            field=models.CharField(max_length=300),
        ),
    ]
