# Generated by Django 5.1.2 on 2024-12-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_app_app_name_alter_app_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_version',
            field=models.CharField(max_length=20),
        ),
    ]
