# Generated by Django 5.1.2 on 2025-01-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Unpublished', 'Unpublished')], default='Pending', max_length=50),
        ),
    ]
